/**
 * facts.js, "náhodná kravina, nesouvisí s ničím".
 *
 * Zobrazuje se nenápadně pod check-in tlačítkem, pokaždé jiná (při každém
 * načtení). Úplně random témata, schválně bez vazby na zónu. Perličky o zóně
 * žijí v zones.js, tohle je čistá sranda navíc.
 *
 * Várky 1 a 2. Cíl je 500+, nabaluje se postupně. Jen fakta, co se dají ověřit.
 * Žádné pomlčky jako interpunkce.
 */

export const FACTS = [
  // Zvířata
  "Vydry spí tak, že se drží za packy, aby je proud neodnesl od sebe. I zvířata řeší, ať je parťák ráno pořád vedle.",
  "Chobotnice má tři srdce a modrou krev. Zní to jako výmluva, ale ne, oni prostě takhle jedou.",
  "Vombatí hovna jsou do kostky. Vážně hranatá. A teď o tom víme oba.",
  "Krokodýl neumí vyplazit jazyk, má ho přirostlý. V soutěži o nejtrapnější grimasu tě aspoň neporazí.",
  "Mořský koník je jediný, kde rodí samec. Někde se to prostě dělá jinak a funguje to.",
  "Lenochod plave asi třikrát rychleji, než leze po zemi. Taky se ve vodě cítíš líp než ráno v posteli?",
  "Plameňáci se rodí šedí. Růžoví jsou až z toho, co žerou. Kdybys jedl jako oni, taky by sis barvu nevybral.",
  "Krevety mají srdce v hlavě. Doslova. Takže když je někdo krevetí mozek, je to vlastně romantik.",
  "Motýli ochutnávají nohama. Představ si, že bys musel stoupnout do pizzy, abys věděl, jestli je dobrá.",
  "Kozy mají obdélníkové zorničky. Koukni jedné do očí a pak se pokus usnout.",
  "Sovy nedokážou hýbat očima, točí celou hlavou. Proto se na tebe dívají, jako bys jim dlužil peníze.",
  "Pštrosí oko je větší než jeho mozek. Někdy to tak má i člověk ve čtyři ráno.",
  "Koala má otisky prstů tak podobné lidským, že by mohla zmást vyšetřovatele. Perfektní alibi.",
  "Polární medvěd má černou kůži a průhlednou srst. Bílý je jen naoko, jako tvůj Instagram.",
  "Hroch se potí červenohnědou tekutinou, co mu funguje jako opalovací krém. Sám si vyrábí SPF.",
  "Žirafa má v krku stejně obratlů jako ty, sedm. Jen každý je velký jako tvoje předloktí.",
  "Mořská vydra má pod paží kapsu, kde nosí oblíbený kámen. Ty máš na to ledvinku.",
  "Mořská hvězdice nemá mozek a žije v pohodě. Inspirace na zbytek noci.",
  "Netopýři jsou jediní savci, co doopravdy létají. Veverka letuška jen plachtí a fláká to.",
  "Krysy se smějí, když je lechtáš. Jen tak vysoko, že to lidské ucho neslyší.",
  "Delfíni spí s půlkou mozku. Druhá hlídá. Taky tak jedeš na rodinných oslavách.",
  "Delfíni se oslovují vlastními jmény, takovým pískáním. Pamatují si jméno líp než ty ve tři ráno.",
  "Krávy mají nejlepší kámošky a když je od sebe oddělíš, jsou ve stresu. Tvoje parta na Silvestra je v podstatě stádo.",
  "Tučňáci si při námluvách nosí kamínky. Nejlepší kámen jde na rande. Levnější než večeře.",
  "Lenochod tráví tak pomalu, že v zimě může umřít hlady s plným břichem. Relatable obsah pro gauč.",
  "Axolotl si umí dorůst nohu, ocas i kus srdce a přitom se pořád usmívá. Mě už asi nic nedoroste.",
  "Mořská okurka umí v nebezpečí vyvrhnout vnitřnosti a pak si je doroste. Tvoje kocovina je proti tomu slabota.",
  "Včely umí rozeznat lidské obličeje. Ta jedna, co tě loni bodla, si tě možná pamatuje.",
  "Vrány si pamatují obličeje lidí, co jim ublížili, a řeknou to ostatním vránám. Drby na úrovni.",
  "Sloni se bojí včel. Pět tun svalů a stačí jim bzučení. Každý máme svou slabinu.",
  "Šváb přežije bez hlavy klidně týden. Nakonec umře na žízeň, protože nemá čím pít.",
  "Komár zabije každý rok víc lidí než jakékoliv jiné zvíře. Žraloci jsou proti němu amatéři.",
  "Žraloci jsou starší než stromy. Byli tu dřív než první les.",
  "Žraloci nemají v těle jedinou kost. Jen chrupavku, jako tvoje ucho.",
  "Hlemýžď má tisíce drobných zoubků. Usmívá se na tebe celou pilou.",
  "Některé želvy umí dýchat zadkem. Vědecky se tomu říká kloakální dýchání. Ty víš, jak se tomu říká doopravdy.",
  "Skokan lesní v zimě úplně zmrzne, srdce mu přestane bít, a na jaře rozmrzne a skáče dál. Jako ty po Silvestru.",
  "Ptáci jsou dinosauři. Když jíš kuřecí křídla, jíš malého dinosaura.",
  "Kočky necítí sladkou chuť. Nemají na ni receptory. Dort pro kočku je jen divná mastná věc.",
  "Jazyk plejtváka obrovského váží zhruba jako slon. Jeden jazyk.",
  "Mravenců je na Zemi tolik, že váží dohromady asi pětinu všech lidí. Pikniky jsou jejich území, ne tvoje.",
  "Klokan neumí pořádně couvat. Jede jen dopředu. Motivační plakát se píše sám.",
  "Zívání je nakažlivé i pro psy. Zívni na psa a uvidíš.",
  "Pandy stráví žvýkáním bambusu klidně půl dne. Je to jejich celá kariéra.",
  "Lvi prospí až dvacet hodin denně. Král zvířat je hlavně král gauče.",
  "Veverky zapomenou spoustu schovaných oříšků a tím omylem sázejí stromy. I chaos umí udělat něco dobrého.",
  "Medúzy jsou tu přes 500 milionů let a mozek nemají žádný. Nech si to projít hlavou, až budeš řešit, jestli jsi génius.",
  "V Austrálii v roce 1932 armáda vyhlásila válku emu. Emu vyhráli.",
  "Ve Švýcarsku je zakázané mít jen jedno morče. Je to společenské zvíře a samo by bylo smutné.",
  "Ve středověku se ve Francii konaly soudy se zvířaty. Prasata dostávala advokáta.",
  "Skupina vran se anglicky jmenuje murder, vražda. Angličtina je metal.",
  "Skotsko má jako národní zvíře jednorožce. Oficiálně.",

  // Jídlo
  "Banán je botanicky bobule. Jahoda ne. Botanici prostě nechtějí, abys byl šťastný.",
  "Avokádo je taky bobule. Takže tvoje avokádový toast je vlastně ovocný salát.",
  "Arašídy nejsou ořechy, jsou to luštěniny. Burákové máslo je fazolová pomazánka.",
  "Mrkev byla původně fialová. Oranžová je až výsledek šlechtění.",
  "Ananas roste skoro dva roky, než dozraje. A ty ho dáš na pizzu.",
  "Kešu roste na konci ovoce, kterému se říká kešu jablko. Ořech visí zespod jako přívěsek.",
  "Na jedné jahodě je kolem dvou stovek semínek. Na povrchu. Nikdo nevěděl, kde je dát jinam.",
  "Med se nekazí. V egyptských hrobkách našli med, co byl po tisících let pořád jedlý.",
  "Kečup se ve třicátých letech 19. století prodával v lékárnách jako lék. Na hranolky to sedí dodnes.",
  "Čokoláda je pro psy jedovatá. Takže jo, celá tabulka je tvoje.",
  "Kukuřičné lupínky vymyslel Kellogg jako nudné jídlo, co mělo lidem utlumit chtíč. Nefunguje to.",
  "Šafrán je nejdražší koření na světě. Na kilo potřebuješ ručně otrhat přes sto tisíc květů.",
  "Hroznové víno rozpůlené v mikrovlnce vyrobí plazmu. Nedělej to. Vážně. Mikrovlnka tě nenávidí.",
  "Pizza Margherita nese jméno italské královny Markéty. Královna, co pojmenovala jídlo ve dvě ráno.",
  "Kostku cukru vymyslel Jakub Kryštof Rad v Dačicích v roce 1843. Prý protože se jeho žena řízla při sekání homole.",

  // Lidské tělo
  "Miminko má kolem tří stovek kostí, dospělý 206. Cestou se srůstají. Ty ses taky trochu srostl s gaučem.",
  "V prstech nemáš žádné svaly. Hýbou s nimi šlachy ze svalů v předloktí. Jsi loutka.",
  "Otisk jazyka máš unikátní jako otisk prstu. Policie ho zatím nesbírá.",
  "Nehty na rukou rostou rychleji než na nohou. Nohy to prostě flákají.",
  "Žaludek si sliznici obnovuje každých pár dní, jinak by strávil sám sebe.",
  "Kdybys rozmotal DNA ze všech svých buněk, vedla by ke Slunci a zpátky mnohokrát.",
  "Ve vesmíru jsi o pár centimetrů vyšší, páteř se roztáhne. Nejlevnější cesta k vyššímu já.",
  "Průměrný člověk si za den prdne zhruba patnáctkrát. Tak nedělej, že ty ne.",
  "Lidé jsou nejspíš jediná zvířata, co se červenají. Ostatní se nemají za co stydět.",

  // Historie
  "Kleopatra žila blíž přistání na Měsíci než stavbě Velké pyramidy. Pyramidy jsou fakt staré.",
  "Univerzita v Oxfordu je starší než aztécký Tenochtitlán. Ty tvoje přednášky jsou starší než říše.",
  "Když se stavěly pyramidy, na jednom ostrově v Arktidě ještě žili mamuti.",
  "Nejkratší válka v historii trvala asi 38 minut. Británie proti Zanzibaru, 1896. Kratší než tvoje rande.",
  "Napoleon nebyl malý. Měl kolem 169 centimetrů, na svou dobu průměr. Malým ho udělala propaganda.",
  "Vikingové neměli na helmách rohy. Ty jim přidělali až kostyméři v 19. století.",
  "Albert Einstein dostal nabídku stát se prezidentem Izraele. Odmítl.",
  "Rusko prodalo Aljašku Americe za 7,2 milionu dolarů. Dneska by za to nekoupils ani pořádný byt v Praze.",
  "Na první fotce s člověkem je chlap, co si zrovna nechával čistit boty. Stál dost dlouho, ostatní se rozmazali.",
  "Plyšový medvídek, teddy bear, nese jméno amerického prezidenta Theodora Roosevelta.",
  "Konzervy existovaly zhruba padesát let, než někdo vymyslel otvírák. Do té doby kladivo a dláto.",
  "Zapalovač byl vynalezen dřív než zápalky. Ano, nejdřív ta složitější věc.",
  "Bublinková fólie měla být původně tapeta. Neprodávala se. Teď ji mačkáš.",
  "Play Doh, ta modelína, byla původně čistič tapet.",
  "Viagra se původně testovala jako lék na srdce. Pacienti si pak stěžovali na vedlejší účinek. Ne moc hlasitě.",
  "Nintendo bylo založené v roce 1889 a vyrábělo hrací karty.",
  "Google se původně jmenoval BackRub. Škrábání zad.",
  "Amazon se měl jmenovat Cadabra. Jako abrakadabra. Jenže právník to po telefonu slyšel jako cadaver, mrtvola.",
  "První video na YouTube se jmenuje Me at the zoo a je o slonech. Osmnáct vteřin.",
  "První SMS v historii zněla Merry Christmas. Poslaná v roce 1992. Od té doby to jde z kopce.",
  "První televizní ovladač se jmenoval Lazy Bones, líná kost. Aspoň upřímné.",
  "Super Mario byl původně tesař a jmenoval se Jumpman. Instalatérem se stal až později.",
  "Pac Man má tvar pizzy, ze které chybí kousek. Tak to aspoň tvrdí jeho autor.",
  "Tetris vymyslel ruský programátor Alexej Pažitnov v roce 1984. Ve volném čase v práci.",
  "Rubikova kostka má přes 43 trilionů možných kombinací. A ty ji neumíš ani jednou.",
  "Řecká hymna má 158 slok. Na stadionu se naštěstí zpívají jen dvě.",
  "Beethoven skládal Devátou symfonii skoro úplně hluchý. Ty neslyšíš ani budík.",
  "Mona Lisa nemá obočí. Ani řasy. Možná je jen zrovna po kosmetičce.",
  "Lego je podle počtu kusů největší výrobce pneumatik na světě. Ty malinké se počítají.",

  // Česko
  "Slovo robot vymyslel Josef Čapek, Karel ho jen použil. Celý svět mluví česky a neví o tom.",
  "Slovo pistole nejspíš pochází z husitské píšťaly. Češi exportují zbraně i slovník.",
  "Strč prst skrz krk je věta bez jediné samohlásky. Cizinci u ní pláčou.",
  "Měkké kontaktní čočky vymyslel Čech Otto Wichterle. Prvně je prý dělal na stavebnici Merkur.",
  "Lodní šroub vynalezl Josef Ressel. Češi bez moře zařídili, aby lodě jezdily.",
  "Kostnice v Sedlci u Kutné Hory má lustr z lidských kostí. Interiérový design úroveň boss.",
  "Češi pijí nejvíc piva na hlavu na světě. Už desítky let v kuse. Jediná tabulka, kde vedeme.",

  // Vesmír a příroda
  "Na Venuši je den delší než rok. Otočí se kolem sebe pomaleji, než oběhne Slunce.",
  "Na Marsu jsou západy slunce modré. Obráceně než u nás.",
  "Lžička hmoty z neutronové hvězdy by vážila zhruba miliardu tun.",
  "Saturn má menší hustotu než voda. Kdybys měl dost velkou vanu, plaval by.",
  "Uran se točí na boku. Kutálí se po oběžné dráze jako kulička.",
  "Jupiter má přes devadesát měsíců. My jeden a ještě se o něj hádáme.",
  "Slunce tvoří přes 99 procent hmotnosti celé Sluneční soustavy. Zbytek jsou drobky.",
  "Na Měsíci zůstalo přes devadesát pytlů s lidskými výkaly z misí Apollo. Pozdrav pro mimozemšťany.",
  "Astronaut Alan Shepard odpálil na Měsíci golfové míčky a tvrdil, že letěly míle a míle. Pozdější analýza: asi čtyřicet metrů. Typický chlap.",
  "Stopy astronautů na Měsíci tam budou miliony let. Nefouká vítr, nic je nesmaže.",
  "Na Zemi je víc stromů než hvězd v Mléčné dráze. Asi tři biliony stromů.",
  "Možných zamíchání balíčku 52 karet je víc než atomů na Zemi. Každé pořádné zamíchání je nejspíš poprvé v historii.",
  "Blesk je žhavější než povrch Slunce. Asi pětkrát.",
  "Voda umí vřít a mrznout zároveň. Říká se tomu trojný bod. Jako tvůj vztah k ex.",
  "Největší poušť na světě je Antarktida. Poušť znamená málo srážek, ne písek.",
  "V Sahaře občas sněží. Vážně.",
  "Přes Amazonku nevede ani jeden most. Celou délku.",
  "Nejvzdálenější bod od středu Země není vrchol Everestu, ale Chimborazo v Ekvádoru. Země je v pase tlustší.",
  "Rusko je rozlohou větší než Pluto. Celá trpasličí planeta.",
  "Austrálie je širší než Měsíc. Měsíc má v průměru asi 3 500 kilometrů, Austrálie přes 4 000.",
  "Monako je menší než Central Park v New Yorku.",
  "Vatikán vypije nejvíc vína na hlavu na světě. Mše se počítají.",
  "Na Novém Zélandu je víc ovcí než lidí. Několikanásobně.",
  "Eiffelova věž je v létě asi o patnáct centimetrů vyšší. Kov se v teple roztahuje.",
  "Na Islandu není od roku 2009 jediný McDonald's. Poslední burger tam prý pořád leží ve vitríně.",
  "Ve Finsku se pořádá mistrovství světa v nošení manželky. Výherce vyhraje manželčinu váhu v pivu.",

  // Várka 2: zvířata
  "Chobotnice mají v chapadlech víc neuronů než v hlavě. Každé chapadlo si trochu myslí samo.",
  "Kočky tráví spánkem zhruba dvě třetiny života. Profesionální úroveň.",
  "Žirafy spí jen pár desítek minut denně, často po krátkých šlofících. Ty po dnešku prospíš i jejich týden.",
  "Kolibřík je jediný pták, co umí létat pozpátku. Couvá líp než ty na parkovišti.",
  "Kuře umí přežít i bez hlavy. Slavný kohout Mike žil ve 40. letech v USA bez hlavy přes rok a jezdil na turné.",
  "Pes prý umí čichem odhadnout, kolik je hodin. Podle toho, jak slábne pach z rána.",
  "Hlemýžď prý umí v suchu spát klidně tři roky v kuse. Mistr v ignorování budíku.",
  "Mravenci nespí jako my, dávají si stovky mikrošlofíků denně. Tak to taky dneska zkus.",
  "Vačice předstírají smrt tak dobře, že u toho i smrdí jako mrtvola. Method acting.",
  "Sloní mláďata si cucají chobot, jako děti palec.",
  "Pavouk skákavka vidí barvy líp než pes.",
  "Delfíní mládě se rodí ocasem napřed, aby se neudusilo.",
  "Hroši neumí plavat. Chodí po dně a odrážejí se, jako bys skákal v bazénu po špičkách.",
  "Kapr si pamatuje víc než tři vteřiny. Mýtus o zlaté rybce s pamětí tří vteřin je blbost, pamatují si měsíce.",
  "Vrány dokážou použít a dokonce vyrobit nástroje. Novokaledonské vrány ohýbají drátky na háčky.",
  "Samice komára pije krev, samec ne. Ten bzučí jen tak pro radost.",
  "Velbloudi nemají v hrbu vodu, ale tuk.",
  "Čichový smysl žraloka zachytí krev ve vodě ve velmi malém ředění. Hlavně v klidu na Silvestra v bazénu.",
  "Krocan se dokáže uzardit. Hlava mu změní barvu podle nálady.",
  "Tygr má pruhovanou i kůži, ne jen srst.",
  "Zebra je černá s bílými pruhy, ne obráceně. Pod srstí má tmavou kůži.",
  "Žába skokan umí polykat i očima. Při polykání je zatlačí dovnitř hlavy.",
  "Mořští koníci se při plavání drží v párech za ocásky.",
  "Klokan novorozenec je velký zhruba jako fazole.",
  "Sovy nemají oči jako koule, ale jako trubky. Proto s nimi nehýbou.",
  "Holub se dokáže naučit rozeznat obrazy Picassa a Moneta. Kulturnější než půlka tvých kámošů.",
  "Bobři mají oranžové zuby. Kvůli železu ve sklovině.",

  // Várka 2: jídlo a pití
  "Šampaňské nesmí nést tohle jméno, pokud nepochází z francouzského regionu Champagne. Jinak je to prostě šumivé víno.",
  "Bublinky v šampusu stoupají v řetízcích kvůli drobným nečistotám ve skle. Úplně čistá sklenička by moc nebublala.",
  "V láhvi šampaňského je tlak zhruba jako v pneumatice náklaďáku. Proto ten korek letí jak raketa.",
  "Korek ze šampaňského umí letět rychlostí až kolem 80 kilometrů za hodinu. Míř od lidí, ne na lustr.",
  "Fortune cookies, koláčky s věštbou, nejsou z Číny. Vymysleli je nejspíš Japonci v Kalifornii.",
  "Nachos vymyslel v Mexiku chlap jménem Ignacio, přezdívaný Nacho. Pojmenoval je po sobě.",
  "Čokoládu se dříve pilo, ne jedlo. Aztékové ji míchali s chilli.",
  "Brambory byly první zelenina vypěstovaná ve vesmíru. V roce 1995 na raketoplánu Columbia.",
  "Jahody nejsou bobule, ale banány, avokáda a lilky ano. Botanika je troll.",
  "Rajče je botanicky ovoce. Kečup je tedy technicky džem.",
  "Pistácie se můžou samy vznítit, když se skladují ve velkém a vlhku. Ořech s temperamentem.",
  "Muškátový oříšek ve velkém množství způsobuje halucinace a dost ošklivou otravu. Necpi to do svařáku po hrstech.",
  "Wasabi v sushi restauracích je skoro vždy křen s barvivem. Pravé wasabi je drahé.",
  "Ananas obsahuje enzym, co rozkládá bílkoviny. Když ho jíš, chvilku jí on tebe.",
  "Sýr je nejkradenější potravina na světě.",
  "Kafe byl kdysi v některých zemích zakázaný jako nebezpečná droga.",
  "Cibule rozplačou proto, že při krájení uvolní plyn, co v oku vytvoří slabou kyselinu.",
  "Nejdražší pizza na světě stála tisíce eur. Měla kaviár a zlaté lupínky. Pořád to byla pizza.",

  // Várka 2: tělo a mozek
  "Mozek sám bolest necítí, nemá v sobě receptory bolesti. Bolí tě všechno kolem, jen on ne.",
  "Mozek spotřebuje zhruba pětinu energie těla, i když váží jen asi dvě procenta.",
  "Lidské oko rozezná zhruba milion odstínů barev.",
  "Smích je nakažlivý. Mozek reaguje na cizí smích přípravou vlastního.",
  "Kýchnutí neumíš udělat s otevřenýma očima. Tělo prostě nechce.",
  "V těle nosíš zhruba kilo bakterií, hlavně ve střevech. Nikdy nejsi sám, ani v noci na gauči.",
  "Lidé sdílí s banánem zhruba polovinu genů. Tak se k nim chovej slušně.",
  "Srdce ti udeří zhruba sto tisíckrát denně. I dneska v noci, i když ho trápíš.",
  "Kosti jsou pevnější než ocel stejné váhy.",
  "Kocovina je z velké části dehydratace a zánět. Voda před spaním je tvůj nejlepší kámoš.",
  "Alkohol tě nezahřeje. Roztáhne cévy, takže se cítíš teplý, ale ve skutečnosti chladneš rychleji.",
  "Lidé jsou jediní savci, co dobrovolně oddalují spánek. Jako ty dneska.",
  "Ve spánku jsi trochu ochrnutý. Tělo vypne svaly, abys nehrál sny naživo.",
  "Zívnutí zchlazuje mozek. Aspoň podle jedné vědecké teorie.",
  "Tvůj nos si zapamatuje víc než bilion vůní. Aspoň podle jednoho odhadu.",

  // Várka 2: historie a lidi
  "Starověcí Egypťané používali jako antikoncepci krokodýlí trus. Doporučujeme raději něco modernějšího.",
  "Římané si čistili zuby močí. Prý to bělilo. Zubní pasta je vynález, co si zaslouží dík.",
  "Ohňostroj vynalezli v Číně zhruba před tisíci lety. Původně měl odhánět zlé duchy.",
  "Ball drop na Times Square se poprvé spustil v roce 1907. Koule tehdy byla ze železa a dřeva.",
  "Julius Caesar posunul nový rok na 1. leden. Do té doby se ve starém Římě začínalo v březnu.",
  "Písnička Auld Lang Syne znamená zhruba za starých časů. Skoro nikdo nezná víc než první sloku.",
  "Kalendář, co používáš, se jmenuje gregoriánský. Rusko na něj přešlo až v roce 1918 a ztratilo pár dní.",
  "V roce 1752 Británie přeskočila jedenáct dní při změně kalendáře. Lidi prý protestovali, ať jim vrátí jejich dny.",
  "Abraham Lincoln je v americké Wrestling Hall of Fame. Měl za sebou kolem tří stovek zápasů.",
  "Albert Einstein nenosil ponožky. Říkal, že stejně dělají díry.",
  "Ve Francii se až do roku 1977 popravovalo gilotinou. Stejný rok, kdy vyšly první Hvězdné války.",
  "Hitlerův synovec William sloužil v americkém námořnictvu proti Německu.",
  "Pyramidy v Gíze nestavěli otroci, ale placení dělníci. Měli i pivo jako součást výplaty.",

  // Várka 2: věda, vesmír a technika
  "Ve vesmíru nejde pořádně brečet. Slzy neodtečou, jen se ti udělá kulička vody na oku.",
  "Astronauti po návratu ze stanice chvilku zapomínají, že věci padají. Pouštějí hrnky na zem.",
  "Na Mezinárodní vesmírné stanici je vidět kolem šestnácti východů slunce denně. Silvestr tam slaví jak chtějí.",
  "Světlo ze Slunce k nám letí zhruba osm minut. Slunce, co vidíš, je osm minut staré.",
  "Některé hvězdy, co vidíš na nebi, už možná neexistují. Jejich světlo je jen hodně staré.",
  "Neptun oběhne Slunce jednou za zhruba 165 let. Od objevu stihl jen jeden celý rok.",
  "Na Venuši prší kyselina sírová, ale k zemi nedopadne, vypaří se cestou. Fakt hnusné místo na dovolenou.",
  "Diamanty můžou pršet na Uranu a Neptunu. Aspoň podle laboratorních pokusů.",
  "Vesmír voní po spáleném steaku a kovu, tvrdí astronauti po výstupu ven.",
  "Kdybys pustil olovnici do díry skrz celou Zemi, letěla by na druhou stranu zhruba 42 minut.",
  "První počítačový bug byl skutečný hmyz. V roce 1947 našli můru v relé počítače Harvard Mark II.",
  "Emoji jako takové vymyslel Japonec Šigetaka Kurita v roce 1999. Původně jich bylo 176.",
  "Hashtag se oficiálně jmenuje oktotorp. Skoro nikdo to neví a ty teď ano.",
  "QWERTY klávesnice měla prý psaní zpomalit, aby se nezasekávaly psací stroje. Je to sporné, ale hezká historka.",
  "Wifi není zkratka a nic neznamená. Je to jen chytlavé jméno od marketingu.",

  // Várka 2: místa a světové kuriozity
  "Kanada má víc jezer než zbytek světa dohromady.",
  "V Japonsku je víc automatů na nápoje než v kterékoliv jiné zemi na hlavu. Jeden na zhruba každých třicet lidí.",
  "Na Islandu existuje aplikace, co ti řekne, jestli nejsi příbuzný s člověkem, se kterým randíš. Malá země, velké riziko.",
  "V Norsku dostal tučňák rytířský titul. Sir Nils Olav je dokonce generál.",
  "V Bolívii je solná pláň tak rovná, že ji satelity používají ke kalibraci.",
  "Francie má nejvíc časových pásem na světě. Díky zámořským územím jich je dvanáct.",
  "Čína má jen jedno časové pásmo, i když je obrovská. Na západě tak vychází slunce klidně v deset ráno.",
  "Nepál má jako jediný na světě vlajku, co není obdélník. Jsou to dva trojúhelníky.",
  "Kazachstán je největší vnitrozemský stát světa. Nikde žádné moře.",
  "V Indii je víc poštovních úřadů než v kterékoliv jiné zemi.",
  "Ve Venezuele je nejvyšší vodopád světa, Salto Angel. Voda se často rozpráší, než dopadne na zem.",
  "V Mexiku se potápí hlavní město. Mexico City klesá o desítky centimetrů za rok na některých místech.",
  "Antarktida nemá vlastní časové pásmo. Každá stanice si jede podle svého.",
  "Na Aljašce je město, kde skoro všichni bydlí v jednom paneláku. Whittier.",
  "Na Havaji je oficiální abeceda jen ze třinácti písmen. Ono to stačí.",
];

export default FACTS;
