/**
 * facts.js, "náhodná kravina, nesouvisí s ničím".
 *
 * Zobrazuje se nenápadně pod check-in tlačítkem, pokaždé jiná (při každém
 * načtení). Úplně random témata, schválně bez vazby na zónu. Perličky o zóně
 * žijí v zones.js, tohle je čistá sranda navíc.
 *
 * Várka 1. Cíl je 500+, nabaluje se postupně. Jen fakta, co se dají ověřit.
 * Žádné pomlčky jako interpunkce.
 */

export const FACTS = [
  // Zvířata
  "Vydry spí tak, že se drží za packy, aby je proud neodnesl od sebe. I zvířata řeší, ať je parťák ráno pořád vedle.",
  "Chobotnice má tři srdce a modrou krev. Zní to jako výmluva, ale ne, oni prostě takhle jedou.",
  "Vombatí hovna jsou do kostky. Vážně hranatá. A teď o tom víme oba.",
  "Krokodýl neumí vyplazit jazyk, má ho přirostlý. V soutěži o nejtrapnější grimasu tě aspoň neporazí.",
  "Mořský koník je jediný, kde rodí samec. Někde se to prostě dělá jinak a funguje to.",
  "Lenochod plave asi třikrát rychleji, než leze po zemi. Taky se ve vodě cítíš líp než ráno v posteli?",
  "Plameňáci se rodí šedí. Růžoví jsou až z toho, co žerou. Kdybys jedl jako oni, taky by sis barvu nevybral.",
  "Krevety mají srdce v hlavě. Doslova. Takže když je někdo krevetí mozek, je to vlastně romantik.",
  "Motýli ochutnávají nohama. Představ si, že bys musel stoupnout do pizzy, abys věděl, jestli je dobrá.",
  "Kozy mají obdélníkové zorničky. Koukni jedné do očí a pak se pokus usnout.",
  "Sovy nedokážou hýbat očima, točí celou hlavou. Proto se na tebe dívají, jako bys jim dlužil peníze.",
  "Pštrosí oko je větší než jeho mozek. Někdy to tak má i člověk ve čtyři ráno.",
  "Koala má otisky prstů tak podobné lidským, že by mohla zmást vyšetřovatele. Perfektní alibi.",
  "Polární medvěd má černou kůži a průhlednou srst. Bílý je jen naoko, jako tvůj Instagram.",
  "Hroch se potí červenohnědou tekutinou, co mu funguje jako opalovací krém. Sám si vyrábí SPF.",
  "Žirafa má v krku stejně obratlů jako ty, sedm. Jen každý je velký jako tvoje předloktí.",
  "Mořská vydra má pod paží kapsu, kde nosí oblíbený kámen. Ty máš na to ledvinku.",
  "Mořská hvězdice nemá mozek a žije v pohodě. Inspirace na zbytek noci.",
  "Netopýři jsou jediní savci, co doopravdy létají. Veverka letuška jen plachtí a fláká to.",
  "Krysy se smějí, když je lechtáš. Jen tak vysoko, že to lidské ucho neslyší.",
  "Delfíni spí s půlkou mozku. Druhá hlídá. Taky tak jedeš na rodinných oslavách.",
  "Delfíni se oslovují vlastními jmény, takovým pískáním. Pamatují si jméno líp než ty ve tři ráno.",
  "Krávy mají nejlepší kámošky a když je od sebe oddělíš, jsou ve stresu. Tvoje parta na Silvestra je v podstatě stádo.",
  "Tučňáci si při námluvách nosí kamínky. Nejlepší kámen jde na rande. Levnější než večeře.",
  "Lenochod tráví tak pomalu, že v zimě může umřít hlady s plným břichem. Relatable obsah pro gauč.",
  "Axolotl si umí dorůst nohu, ocas i kus srdce a přitom se pořád usmívá. Mě už asi nic nedoroste.",
  "Mořská okurka umí v nebezpečí vyvrhnout vnitřnosti a pak si je doroste. Tvoje kocovina je proti tomu slabota.",
  "Včely umí rozeznat lidské obličeje. Ta jedna, co tě loni bodla, si tě možná pamatuje.",
  "Vrány si pamatují obličeje lidí, co jim ublížili, a řeknou to ostatním vránám. Drby na úrovni.",
  "Sloni se bojí včel. Pět tun svalů a stačí jim bzučení. Každý máme svou slabinu.",
  "Šváb přežije bez hlavy klidně týden. Nakonec umře na žízeň, protože nemá čím pít.",
  "Komár zabije každý rok víc lidí než jakékoliv jiné zvíře. Žraloci jsou proti němu amatéři.",
  "Žraloci jsou starší než stromy. Byli tu dřív než první les.",
  "Žraloci nemají v těle jedinou kost. Jen chrupavku, jako tvoje ucho.",
  "Hlemýžď má tisíce drobných zoubků. Usmívá se na tebe celou pilou.",
  "Některé želvy umí dýchat zadkem. Vědecky se tomu říká kloakální dýchání. Ty víš, jak se tomu říká doopravdy.",
  "Skokan lesní v zimě úplně zmrzne, srdce mu přestane bít, a na jaře rozmrzne a skáče dál. Jako ty po Silvestru.",
  "Ptáci jsou dinosauři. Když jíš kuřecí křídla, jíš malého dinosaura.",
  "Kočky necítí sladkou chuť. Nemají na ni receptory. Dort pro kočku je jen divná mastná věc.",
  "Jazyk plejtváka obrovského váží zhruba jako slon. Jeden jazyk.",
  "Mravenců je na Zemi tolik, že váží dohromady asi pětinu všech lidí. Pikniky jsou jejich území, ne tvoje.",
  "Klokan neumí pořádně couvat. Jede jen dopředu. Motivační plakát se píše sám.",
  "Zívání je nakažlivé i pro psy. Zívni na psa a uvidíš.",
  "Pandy stráví žvýkáním bambusu klidně půl dne. Je to jejich celá kariéra.",
  "Lvi prospí až dvacet hodin denně. Král zvířat je hlavně král gauče.",
  "Veverky zapomenou spoustu schovaných oříšků a tím omylem sázejí stromy. I chaos umí udělat něco dobrého.",
  "Medúzy jsou tu přes 500 milionů let a mozek nemají žádný. Nech si to projít hlavou, až budeš řešit, jestli jsi génius.",
  "V Austrálii v roce 1932 armáda vyhlásila válku emu. Emu vyhráli.",
  "Ve Švýcarsku je zakázané mít jen jedno morče. Je to společenské zvíře a samo by bylo smutné.",
  "Ve středověku se ve Francii konaly soudy se zvířaty. Prasata dostávala advokáta.",
  "Skupina vran se anglicky jmenuje murder, vražda. Angličtina je metal.",
  "Skotsko má jako národní zvíře jednorožce. Oficiálně.",

  // Jídlo
  "Banán je botanicky bobule. Jahoda ne. Botanici prostě nechtějí, abys byl šťastný.",
  "Avokádo je taky bobule. Takže tvoje avokádový toast je vlastně ovocný salát.",
  "Arašídy nejsou ořechy, jsou to luštěniny. Burákové máslo je fazolová pomazánka.",
  "Mrkev byla původně fialová. Oranžová je až výsledek šlechtění.",
  "Ananas roste skoro dva roky, než dozraje. A ty ho dáš na pizzu.",
  "Kešu roste na konci ovoce, kterému se říká kešu jablko. Ořech visí zespod jako přívěsek.",
  "Na jedné jahodě je kolem dvou stovek semínek. Na povrchu. Nikdo nevěděl, kde je dát jinam.",
  "Med se nekazí. V egyptských hrobkách našli med, co byl po tisících let pořád jedlý.",
  "Kečup se ve třicátých letech 19. století prodával v lékárnách jako lék. Na hranolky to sedí dodnes.",
  "Čokoláda je pro psy jedovatá. Takže jo, celá tabulka je tvoje.",
  "Kukuřičné lupínky vymyslel Kellogg jako nudné jídlo, co mělo lidem utlumit chtíč. Nefunguje to.",
  "Šafrán je nejdražší koření na světě. Na kilo potřebuješ ručně otrhat přes sto tisíc květů.",
  "Hroznové víno rozpůlené v mikrovlnce vyrobí plazmu. Nedělej to. Vážně. Mikrovlnka tě nenávidí.",
  "Pizza Margherita nese jméno italské královny Markéty. Královna, co pojmenovala jídlo ve dvě ráno.",
  "Kostku cukru vymyslel Jakub Kryštof Rad v Dačicích v roce 1843. Prý protože se jeho žena řízla při sekání homole.",

  // Lidské tělo
  "Miminko má kolem tří stovek kostí, dospělý 206. Cestou se srůstají. Ty ses taky trochu srostl s gaučem.",
  "V prstech nemáš žádné svaly. Hýbou s nimi šlachy ze svalů v předloktí. Jsi loutka.",
  "Otisk jazyka máš unikátní jako otisk prstu. Policie ho zatím nesbírá.",
  "Nehty na rukou rostou rychleji než na nohou. Nohy to prostě flákají.",
  "Žaludek si sliznici obnovuje každých pár dní, jinak by strávil sám sebe.",
  "Kdybys rozmotal DNA ze všech svých buněk, vedla by ke Slunci a zpátky mnohokrát.",
  "Ve vesmíru jsi o pár centimetrů vyšší, páteř se roztáhne. Nejlevnější cesta k vyššímu já.",
  "Průměrný člověk si za den prdne zhruba patnáctkrát. Tak nedělej, že ty ne.",
  "Lidé jsou nejspíš jediná zvířata, co se červenají. Ostatní se nemají za co stydět.",

  // Historie
  "Kleopatra žila blíž přistání na Měsíci než stavbě Velké pyramidy. Pyramidy jsou fakt staré.",
  "Univerzita v Oxfordu je starší než aztécký Tenochtitlán. Ty tvoje přednášky jsou starší než říše.",
  "Když se stavěly pyramidy, na jednom ostrově v Arktidě ještě žili mamuti.",
  "Nejkratší válka v historii trvala asi 38 minut. Británie proti Zanzibaru, 1896. Kratší než tvoje rande.",
  "Napoleon nebyl malý. Měl kolem 169 centimetrů, na svou dobu průměr. Malým ho udělala propaganda.",
  "Vikingové neměli na helmách rohy. Ty jim přidělali až kostyméři v 19. století.",
  "Albert Einstein dostal nabídku stát se prezidentem Izraele. Odmítl.",
  "Rusko prodalo Aljašku Americe za 7,2 milionu dolarů. Dneska by za to nekoupils ani pořádný byt v Praze.",
  "Na první fotce s člověkem je chlap, co si zrovna nechával čistit boty. Stál dost dlouho, ostatní se rozmazali.",
  "Plyšový medvídek, teddy bear, nese jméno amerického prezidenta Theodora Roosevelta.",
  "Konzervy existovaly zhruba padesát let, než někdo vymyslel otvírák. Do té doby kladivo a dláto.",
  "Zapalovač byl vynalezen dřív než zápalky. Ano, nejdřív ta složitější věc.",
  "Bublinková fólie měla být původně tapeta. Neprodávala se. Teď ji mačkáš.",
  "Play Doh, ta modelína, byla původně čistič tapet.",
  "Viagra se původně testovala jako lék na srdce. Pacienti si pak stěžovali na vedlejší účinek. Ne moc hlasitě.",
  "Nintendo bylo založené v roce 1889 a vyrábělo hrací karty.",
  "Google se původně jmenoval BackRub. Škrábání zad.",
  "Amazon se měl jmenovat Cadabra. Jako abrakadabra. Jenže právník to po telefonu slyšel jako cadaver, mrtvola.",
  "První video na YouTube se jmenuje Me at the zoo a je o slonech. Osmnáct vteřin.",
  "První SMS v historii zněla Merry Christmas. Poslaná v roce 1992. Od té doby to jde z kopce.",
  "První televizní ovladač se jmenoval Lazy Bones, líná kost. Aspoň upřímné.",
  "Super Mario byl původně tesař a jmenoval se Jumpman. Instalatérem se stal až později.",
  "Pac Man má tvar pizzy, ze které chybí kousek. Tak to aspoň tvrdí jeho autor.",
  "Tetris vymyslel ruský programátor Alexej Pažitnov v roce 1984. Ve volném čase v práci.",
  "Rubikova kostka má přes 43 trilionů možných kombinací. A ty ji neumíš ani jednou.",
  "Řecká hymna má 158 slok. Na stadionu se naštěstí zpívají jen dvě.",
  "Beethoven skládal Devátou symfonii skoro úplně hluchý. Ty neslyšíš ani budík.",
  "Mona Lisa nemá obočí. Ani řasy. Možná je jen zrovna po kosmetičce.",
  "Lego je podle počtu kusů největší výrobce pneumatik na světě. Ty malinké se počítají.",

  // Česko
  "Slovo robot vymyslel Josef Čapek, Karel ho jen použil. Celý svět mluví česky a neví o tom.",
  "Slovo pistole nejspíš pochází z husitské píšťaly. Češi exportují zbraně i slovník.",
  "Strč prst skrz krk je věta bez jediné samohlásky. Cizinci u ní pláčou.",
  "Měkké kontaktní čočky vymyslel Čech Otto Wichterle. Prvně je prý dělal na stavebnici Merkur.",
  "Lodní šroub vynalezl Josef Ressel. Češi bez moře zařídili, aby lodě jezdily.",
  "Kostnice v Sedlci u Kutné Hory má lustr z lidských kostí. Interiérový design úroveň boss.",
  "Češi pijí nejvíc piva na hlavu na světě. Už desítky let v kuse. Jediná tabulka, kde vedeme.",

  // Vesmír a příroda
  "Na Venuši je den delší než rok. Otočí se kolem sebe pomaleji, než oběhne Slunce.",
  "Na Marsu jsou západy slunce modré. Obráceně než u nás.",
  "Lžička hmoty z neutronové hvězdy by vážila zhruba miliardu tun.",
  "Saturn má menší hustotu než voda. Kdybys měl dost velkou vanu, plaval by.",
  "Uran se točí na boku. Kutálí se po oběžné dráze jako kulička.",
  "Jupiter má přes devadesát měsíců. My jeden a ještě se o něj hádáme.",
  "Slunce tvoří přes 99 procent hmotnosti celé Sluneční soustavy. Zbytek jsou drobky.",
  "Na Měsíci zůstalo přes devadesát pytlů s lidskými výkaly z misí Apollo. Pozdrav pro mimozemšťany.",
  "Astronaut Alan Shepard odpálil na Měsíci golfové míčky a tvrdil, že letěly míle a míle. Pozdější analýza: asi čtyřicet metrů. Typický chlap.",
  "Stopy astronautů na Měsíci tam budou miliony let. Nefouká vítr, nic je nesmaže.",
  "Na Zemi je víc stromů než hvězd v Mléčné dráze. Asi tři biliony stromů.",
  "Možných zamíchání balíčku 52 karet je víc než atomů na Zemi. Každé pořádné zamíchání je nejspíš poprvé v historii.",
  "Blesk je žhavější než povrch Slunce. Asi pětkrát.",
  "Voda umí vřít a mrznout zároveň. Říká se tomu trojný bod. Jako tvůj vztah k ex.",
  "Největší poušť na světě je Antarktida. Poušť znamená málo srážek, ne písek.",
  "V Sahaře občas sněží. Vážně.",
  "Přes Amazonku nevede ani jeden most. Celou délku.",
  "Nejvzdálenější bod od středu Země není vrchol Everestu, ale Chimborazo v Ekvádoru. Země je v pase tlustší.",
  "Rusko je rozlohou větší než Pluto. Celá trpasličí planeta.",
  "Austrálie je širší než Měsíc. Měsíc má v průměru asi 3 500 kilometrů, Austrálie přes 4 000.",
  "Monako je menší než Central Park v New Yorku.",
  "Vatikán vypije nejvíc vína na hlavu na světě. Mše se počítají.",
  "Na Novém Zélandu je víc ovcí než lidí. Několikanásobně.",
  "Eiffelova věž je v létě asi o patnáct centimetrů vyšší. Kov se v teple roztahuje.",
  "Na Islandu není od roku 2009 jediný McDonald's. Poslední burger tam prý pořád leží ve vitríně.",
  "Ve Finsku se pořádá mistrovství světa v nošení manželky. Výherce vyhraje manželčinu váhu v pivu.",
];

export default FACTS;
