/**
 * zones.js — Zone data module for the New Year Bundle PWA (Phase 1 MVP).
 *
 * Exports:
 *   ZONES (named export) and the same array as the default export.
 *
 * Shape of each entry:
 *   {
 *     id: string,                 // stable slug, used as key in state/localStorage
 *     czTime: string,             // 'HH:MM', the CZ (Czech) time this zone hits midnight
 *     label: string,              // display name; merge groups show the combined name
 *     utcOffset: string,          // e.g. '+14 / +13:45' for merges, '+1' for single zones
 *     merge: string | null,       // short note when this entry collapses several zones; else null
 *     intensity: 'L'|'M'|'H'|'MEGA', // L klid, M stredni, H akcni, MEGA kotva noci
 *     tradition: string,          // what people traditionally do there
 *     perlicka: string,           // the surprising "ty vole to jsem nevedel" fact
 *     challenge: string | null,   // instructions to the reader; null when the zone does not celebrate
 *     symbolicPenaltyNote: string | null, // lower-score symbolic fallback, worded as a PENALTY; null when no challenge
 *     celebrates: boolean         // false ONLY for Afghanistan and Iran (Nowruz, not Jan 1)
 *   }
 *
 * Ordering: chronological by real midnight (CZ time), 37 zones collapsed into
 * EXACTLY 33 check-in points via 5 merge groups. The merge rule: zones whose
 * real midnights are <= 15 min apart share one check-in and one activity, so one
 * photo/video covers the whole group with no penalty.
 *
 * Style note for whoever edits this: every string here is user-facing. Keep it
 * short, info-first, talking straight to the reader. NO dashes used as
 * punctuation anywhere (no '-', en dash, em dash). Explain foreign words inline.
 */

export const ZONES = [
  {
    id: "kiribati-chatham",
    czTime: "11:00",
    label: "Kiribati + Chatham Islands",
    utcOffset: "+14 / +13:45",
    merge: "Merge skupina: Kiribati + Chatham Islands. Jedna fotka pokryje obě, bez penalizace.",
    intensity: "L",
    tradition: "Tady začíná celá planeta. Kiribati vidí nový rok jako první místo na Zemi, Chathamy jen o kousek později. Lidi se scházejí u moře, zpívají a čekají na první východ slunce roku.",
    perlicka: "Kiribati si ten posun vyloženě vylobbovalo. Dřív šla datová hranice přímo přes stát, takže jedna půlka ostrovů žila o den napřed než druhá. V roce 1995 prezident čáru prostě posunul, aby byla země celá na stejném datu. Vedlejší efekt: Kiribati se stalo prvním místem, co vidí každý nový rok. Chathamy k tomu přihodily svůj slavný offset **+13:45**, jeden z mála na světě, co běží na čtvrthodiny. Ty vole, oni si čas doslova ušili na míru.",
    challenge: "Jsi úplně první člověk v téhle hře, co vítá rok. Zvedni skleničku směrem na východ, tam kde za pár hodin vyjde slunce. Řekni nahlas jednu věc, co od nového roku čekáš. Vyfoť přípitek a pošli check-in.",
    symbolicPenaltyNote: "Když se ti nechce ven ani k oknu, stačí přípitek vsedě na gauči. Je to ale lajná verze, dostaneš míň bodů než za přípitek na čerstvém vzduchu.",
    celebrates: true,
  },
  {
    id: "tonga-nz",
    czTime: "12:00",
    label: "Tonga + Nový Zéland",
    utcOffset: "+13",
    merge: "Merge skupina: Tonga + Nový Zéland. Jeden check-in, jedna fotka pro oba.",
    intensity: "M",
    tradition: "Na Tonze se jde o půlnoci do kostela a zpívá se. Na Novém Zélandu to řeší Sky Tower v Aucklandu obřím ohňostrojem. Church versus věž, dva viby, jeden čas.",
    perlicka: "Perlička se chystá. Zatím ti musí stačit, že TADY zrovna bouchají šampus.",
    challenge: "Vyber si svůj vibe: ztlum světla a dej si tichou minutu jako v kostele, nebo pusť nahlas ohňostrojové video a oslavuj jak Sky Tower. Pak pošli check-in s tím, cos zvolil.",
    symbolicPenaltyNote: "Můžeš jen napsat, co by sis vybral, bez reálné akce. Je to symbolická verze za míň bodů, protože nic reálně neuděláš.",
    celebrates: true,
  },
  {
    id: "sydney",
    czTime: "14:00",
    label: "Sydney, Austrálie",
    utcOffset: "+11 (letní čas)",
    merge: null,
    intensity: "H",
    tradition: "Sydney je ten ohňostroj, co znáš z každého novoročního sestřihu. Statisíce lidí u přístavu, ohňostroj z mostu Harbour Bridge, celosvětový live stream.",
    perlicka: "Perlička se chystá. Zatím ti musí stačit, že TADY zrovna bouchají šampus.",
    challenge: "Pusť si live stream ohňostroje ze Sydney (běží každý rok naživo). Koukni aspoň minutu a chovej se, jako bys tam stál. Screenshot streamu je tvůj check-in.",
    symbolicPenaltyNote: "Když stream nenajdeš, stačí starší video z loňska. Bere se to jako náhradní verze za míň bodů, protože to není naživo.",
    celebrates: true,
  },
  {
    id: "adelaide",
    czTime: "14:30",
    label: "Adelaide, Austrálie",
    utcOffset: "+10:30 (letní čas)",
    merge: null,
    intensity: "L",
    tradition: "Adelaide jede klidnější verzi. Žádný mega dav, spíš rodina, zahrada, pohoda. Je to chvíle na zamyšlení, ne na randál.",
    perlicka: "Perlička se chystá. Zatím ti musí stačit, že TADY zrovna bouchají šampus.",
    challenge: "Vem si na minutu deníček nebo poznámky v telefonu. Napiš jednu větu: co chceš, aby tě tenhle rok naučil. Fotka té věty je check-in.",
    symbolicPenaltyNote: "Můžeš to jen říct nahlas místo napsání. Je to verze za míň bodů, protože nic nezůstane.",
    celebrates: true,
  },
  {
    id: "brisbane",
    czTime: "15:00",
    label: "Brisbane, Austrálie",
    utcOffset: "+10",
    merge: null,
    intensity: "M",
    tradition: "Brisbane slaví v plném létě u řeky. Grilovačky, pivo, teplá noc. Pro tebe v lednové zimě je to lehké sci-fi.",
    perlicka: "Perlička se chystá. Zatím ti musí stačit, že TADY zrovna bouchají šampus.",
    challenge: "Oslav fakt dvojité půlnoci: dej si přípitek za jejich novou hodinu a pak hned za svou další zónu. Dva loky, jedna fotka, pošli check-in.",
    symbolicPenaltyNote: "Když nemáš co pít, zvedni aspoň prázdnou skleničku. Symbolická verze za míň bodů, protože gesto bez obsahu je slabší flex.",
    celebrates: true,
  },
  {
    id: "darwin",
    czTime: "15:30",
    label: "Darwin, Austrálie",
    utcOffset: "+9:30",
    merge: null,
    intensity: "M",
    tradition: "Darwin je tropický sever Austrálie, vedro a dusno i o půlnoci. Oslavy jsou neformální, hodně hudby a venkovních akcí.",
    perlicka: "Perlička se chystá. Zatím ti musí stačit, že TADY zrovna bouchají šampus.",
    challenge: "Tohle je zastávka na playlist. Hoď do příběhu nebo do DM jeden song, co ti má dělat soundtrack ke zbytku noci. Link nebo screenshot je tvůj check-in.",
    symbolicPenaltyNote: "Když link neposíláš, napiš aspoň jméno písničky. Je to náhradní verze za míň bodů, protože ostatní si to nepustí.",
    celebrates: true,
  },
  {
    id: "japonsko-eucla",
    czTime: "16:00",
    label: "Japonsko + Eucla",
    utcOffset: "+9 / +8:45",
    merge: "Merge skupina: Japonsko + Eucla. Jedna fotka pokryje obě zóny.",
    intensity: "L",
    tradition: "V Japonsku zní o půlnoci zvony v chrámech, přesně 108 úderů. Je to tiché, pomalé, skoro meditativní. Eucla je naproti tomu doslova skoro prázdná poušť na kraji Austrálie se svým vlastním podivným časem.",
    perlicka: "Těch **108 úderů** zvonu není náhodné číslo. V buddhismu je to počet pozemských tužeb a slabostí, co člověka trápí. Každý úder jednu symbolicky smaže, abys do nového roku šel čistý. A Eucla? Tam žije v podstatě hrstka lidí a drží si časové pásmo **+8:45**, které nikdo jiný na světě nepoužívá. Je to jedna z nejprázdnějších obydlených zón planety, co má vlastní čas skoro jen sama pro sebe. Ty vole, celé pásmo pro pár baráků u silnice.",
    challenge: "Teď je čas na ticho. Zavři oči a nadechni se 108krát? Ne, to je moc. Nadechni se pomalu desetkrát a u každého výdechu pusť jednu věc, co tě ten rok štvala. Pak pošli check-in se slovem, co ti po tom zbylo.",
    symbolicPenaltyNote: "Když se ti deset nádechů nechce, dej aspoň jeden pořádný. Je to verze za míň bodů, protože klid se nedá odbýt za tři vteřiny.",
    celebrates: true,
  },
  {
    id: "filipiny",
    czTime: "17:00",
    label: "Filipíny",
    utcOffset: "+8",
    merge: null,
    intensity: "H",
    tradition: "Na Filipínách je o půlnoci randál povinnost. Troubí se, bouchá, pouští se hudba naplno. Hluk má odehnat smůlu. A děcka skáčou, aby vyrostla.",
    perlicka: "Perlička se chystá. Zatím ti musí stačit, že TADY zrovna bouchají šampus.",
    challenge: "Udělej na deset vteřin co největší kravál, co ti byt dovolí. Pak třikrát vyskoč co nejvýš. Video toho chaosu je tvůj check-in.",
    symbolicPenaltyNote: "Když máš pod sebou spící sousedy, stačí tichý výskok bez randálu. Symbolická verze za míň bodů, protože půlka té tradice je právě ten rámus.",
    celebrates: true,
  },
  {
    id: "thajsko",
    czTime: "18:00",
    label: "Thajsko",
    utcOffset: "+7",
    merge: null,
    intensity: "M",
    tradition: "Thajsko slaví 1. ledna i svůj vlastní vodní nový rok Songkran v dubnu. Lednová noc je o chrámech, lampionech a přání pro další rok.",
    perlicka: "Perlička se chystá. Zatím ti musí stačit, že TADY zrovna bouchají šampus.",
    challenge: "Napiš zprávu někomu, s kým jsi dlouho nemluvil. Fakt ji odešli, ne jen naťukej. Screenshot odeslané zprávy (text můžeš zakrýt) je check-in.",
    symbolicPenaltyNote: "Když si fakt netroufneš odeslat, naťukej ji aspoň celou a ulož. Je to verze za míň bodů, protože neodeslaná zpráva nikomu neudělá radost.",
    celebrates: true,
  },
  {
    id: "myanmar",
    czTime: "18:30",
    label: "Myanmar",
    utcOffset: "+6:30",
    merge: null,
    intensity: "L",
    tradition: "Myanmar jede klidnou, spíš duchovní verzi. Svíčky, vděčnost, chvíle ticha. Žádné bouchání, spíš usebrání.",
    perlicka: "Perlička se chystá. Zatím ti musí stačit, že TADY zrovna bouchají šampus.",
    challenge: "Zapal svíčku (nebo rozsviť svíčku v telefonu, no judgment). Řekni nahlas tři věci, za které jsi letos vděčný. Fotka plamínku je tvůj check-in.",
    symbolicPenaltyNote: "Když nemáš svíčku ani appku, stačí tři věci říct potmě. Verze za míň bodů, protože světýlko k tomu patří.",
    celebrates: true,
  },
  {
    id: "banglades-nepal-indie",
    czTime: "19:00",
    label: "Bangladéš + Nepál + Indie",
    utcOffset: "+6 / +5:45 / +5:30",
    merge: "Merge skupina (3 zóny): Bangladéš, Nepál a Indie slaví pár minut po sobě. Jeden společný check-in, hlavní aktivita je indická: pálení figuríny. Jedno video pokryje celou trojici.",
    intensity: "M",
    tradition: "Bangladéš a Nepál mají svůj check-in jen jako alive check. Hlavní akce je z Indie: na mnoha místech se o půlnoci pálí figurína starého roku, aby s ní shořelo všechno špatné. Nepál má navíc slavný čas +5:45, jeden z mála čtvrthodinových na světě.",
    perlicka: "Perlička se chystá. Zatím ti musí stačit, že TADY zrovna bouchají šampus.",
    challenge: "Napiš na papír jednu věc ze starého roku, co má definitivně skončit. Pak papír spal (bezpečně, do dřezu nebo popelníku) nebo roztrhej na malé kousky. Video pálení nebo trhání je check-in za celou trojici.",
    symbolicPenaltyNote: "Když nemůžeš nic pálit, aspoň papír roztrhej a vyhoď. Je to verze za míň bodů, protože oheň má větší říz než koš.",
    celebrates: true,
  },
  {
    id: "uzbekistan",
    czTime: "19:30",
    label: "Uzbekistán",
    utcOffset: "+5",
    merge: null,
    intensity: "M",
    tradition: "Uzbekistán slaví nový rok vesele, s rodinou a bohatými stoly. Je to první z trojice, co tě navádí k ruské MEGA kotvě ve 22:00.",
    perlicka: "Perlička se chystá. Zatím ti musí stačit, že TADY zrovna bouchají šampus.",
    challenge: "Řekni si přání potichu do skleničky, než se napiješ. Jedno konkrétní, ne obecné hovno typu 'ať je líp'. Fotka skleničky je check-in.",
    symbolicPenaltyNote: "Když zrovna nepiješ, pošeptej přání do dlaně. Verze za míň bodů, protože sklenička k tomu patří.",
    celebrates: true,
  },
  {
    id: "afghanistan",
    czTime: "20:00",
    label: "Afghánistán",
    utcOffset: "+4:30",
    merge: null,
    intensity: "L",
    tradition: "Tady se dneska nic neslaví, a je to tak schválně. Afghánistán nebere 1. leden jako nový rok. Jejich skutečný nový rok je Nowruz (Nowruz = perské oslavy nového roku na jarní rovnodennost v březnu). Takže žádná výzva, jenom pauza. Dej si vodu, protáhni se, srovnej dech. Za chvíli jedeš dál.",
    perlicka: "Afghánistán používá offset **+4:30**, čtvrthodinové pásmo, které sdílí v podstatě jen s Íránem jako sousedem v téhle části noci. A protože oba slaví Nowruz na jaře, máš v programu dvě tiché zóny po sobě. Nejsou to díry v plánu, jsou to schválně plánované oddechy.",
    challenge: null,
    symbolicPenaltyNote: null,
    celebrates: false,
  },
  {
    id: "azerbajdzan",
    czTime: "20:30",
    label: "Ázerbájdžán",
    utcOffset: "+4",
    merge: null,
    intensity: "M",
    tradition: "Ázerbájdžán slaví s ohněm. Skáče se přes malé ohníčky nebo svíčky pro štěstí a očistu do nového roku. Druhá zastávka na cestě k ruské MEGA kotvě.",
    perlicka: "Perlička se chystá. Zatím ti musí stačit, že TADY zrovna bouchají šampus.",
    challenge: "Přeskoč symbolicky plamínek: polož na zem zapálenou svíčku a opatrně ji překroč (nebo ji obejdi, když je ti to blbé). Fotka nebo video skoku je check-in.",
    symbolicPenaltyNote: "Když nechceš oheň vůbec, překroč aspoň rozsvícený telefon na zemi. Verze za míň bodů, protože plamínek dělá půlku kouzla.",
    celebrates: true,
  },
  {
    id: "iran",
    czTime: "21:00",
    label: "Írán",
    utcOffset: "+3:30",
    merge: null,
    intensity: "L",
    tradition: "Stejně jako Afghánistán, i Írán dneska záměrně neslaví. Jejich nový rok je Nowruz na jaře, ne 1. leden. Takže zase pauza, ne výzva. Tohle je tvoje poslední klidná zóna, než udeří ruská MEGA kotva ve 22:00. Nalej si vodu a nadechni, hned to začne.",
    perlicka: "Írán má u Nowruzu stůl zvaný Haft-Sin (Haft-Sin = stůl se sedmi věcmi, jejichž perský název začíná na písmeno S). Každá z těch sedmi věcí stojí za něco jiného, třeba zdraví, lásku nebo trpělivost. S lednovým Silvestrem to nemá nic společného, a právě proto tady dneska schválně nic neděláš.",
    challenge: null,
    symbolicPenaltyNote: null,
    celebrates: false,
  },
  {
    id: "rusko",
    czTime: "22:00",
    label: "Rusko",
    utcOffset: "+3",
    merge: null,
    intensity: "MEGA",
    tradition: "Tohle je první velká kotva noci. V Rusku odbíjí Kremelské hodiny dvanáct úderů a celá země u toho stojí se skleničkou. Projev prezidenta, pak odbíjení, pak šampus. Navedlo tě sem trio Uzbekistán, Ázerbájdžán, Írán.",
    perlicka: "Existuje ruská tradice, u které si napíšeš přání na papírek, zapálíš ho, popel nasypeš do sklenice šampusu a vypiješ to celé, než dozní dvanáctý úder. Jo, vážně pijou popel. A ty údery nejsou jen efekt: mezi prvním a dvanáctým máš podle pověry zvládnout si něco popřát, aby se to splnilo. Takže zatímco ty koukáš na odpočet, Rusové o půlnoci doslova závodí s hodinami. Ty vole, nový rok jako extrémní sport.",
    challenge: "Odpočítej nahlas od dvanácti do nuly, jako by zrovna odbíjely Kremelské hodiny. Do nuly stihni vyslovit jedno konkrétní přání na celý rok. Video odpočtu s přáním na konci je tvůj check-in téhle MEGA zóny.",
    symbolicPenaltyNote: "Když se ti nechce nahlas, odpočítej aspoň v hlavě a přání napiš do zprávy. Verze za míň bodů, protože MEGA kotva si zaslouží tvůj hlas, ne jen palce.",
    celebrates: true,
  },
  {
    id: "recko",
    czTime: "23:00",
    label: "Řecko",
    utcOffset: "+2",
    merge: null,
    intensity: "M",
    tradition: "V Řecku se o půlnoci hraje karty a sází se, prý kdo vyhraje, bude mít šťastný rok. Taky se peče koláč s mincí uvnitř, kdo ji najde, má kliku.",
    perlicka: "Perlička se chystá. Zatím ti musí stačit, že TADY zrovna bouchají šampus.",
    challenge: "Pošli do DM nebo napiš na papír jedno trapné tajemství z letoška. Nemusí být vážné, čím blbější, tím líp. Screenshot nebo fotka (klidně rozmazaná) je check-in.",
    symbolicPenaltyNote: "Když si netroufneš, napiš aspoň 'tohle bych nikomu neřekl' a jeden emoji. Verze za míň bodů, protože bez obsahu je to jen náznak.",
    celebrates: true,
  },
  {
    id: "cesko",
    czTime: "00:00",
    label: "Česká republika",
    utcOffset: "+1",
    merge: null,
    intensity: "MEGA",
    tradition: "Teď je tvoje domácí půlnoc. Přípitek, ohňostroje za oknem, rozkrojené jablko (hvězdička uvnitř = štěstí, křížek = smůla) a polibek pro štěstí. Tohle je tvoje MEGA zóna, tak si ji fakt užij. Aktivita je schválně minimální, ať slavíš a nekoukáš do telefonu.",
    perlicka: "Perlička se chystá. Zatím ti musí stačit, že TADY zrovna bouchají šampus.",
    challenge: "Žádný složitý úkol, dneska je to o tobě. Připij si, rozkroj jablko napříč a koukni na hvězdičku uvnitř, dej pusu komukoliv po ruce (i psovi, no judgment). Jedna fotka přípitku je tvůj check-in.",
    symbolicPenaltyNote: "Když nemáš jablko ani s kým si připít, stačí přípitek s vodou sám sobě. Verze za míň bodů, protože domácí MEGA si zaslouží aspoň pořádnou skleničku.",
    celebrates: true,
  },
  {
    id: "skotsko",
    czTime: "01:00",
    label: "Skotsko",
    utcOffset: "0",
    merge: null,
    intensity: "M",
    tradition: "Skotský nový rok se jmenuje Hogmanay. Zpívá se Auld Lang Syne, všichni se chytí za ruce v kruhu, a existuje zvyk first-footing: první host roku má přinést dárek pro štěstí.",
    perlicka: "Perlička se chystá. Zatím ti musí stačit, že TADY zrovna bouchají šampus.",
    challenge: "Pusť si Auld Lang Syne (tu písničku znáš, i když nevíš, že ji znáš). Zazpívej refrén nahlas, klidně falešně. Video nebo audio tvého zpěvu je check-in.",
    symbolicPenaltyNote: "Když fakt nezpíváš, pusť aspoň píseň a pošli screenshot přehrávače. Verze za míň bodů, protože zpěv je celá pointa.",
    celebrates: true,
  },
  {
    id: "kapverdy",
    czTime: "02:00",
    label: "Kapverdy",
    utcOffset: "-1",
    merge: null,
    intensity: "M",
    tradition: "Kapverdy jedou nový rok v rytmu. Hraje se funaná, místní tanec plný energie, a tančí se dlouho do noci u pobřeží.",
    perlicka: "Perlička se chystá. Zatím ti musí stačit, že TADY zrovna bouchají šampus.",
    challenge: "Pusť jakoukoliv svižnou písničku a tancuj aspoň třicet vteřin. Nikdo tě nehodnotí, ty vole, hlavně se hýbej. Video tance je check-in.",
    symbolicPenaltyNote: "Když fakt nemůžeš tančit, aspoň pořádně podupej do rytmu vsedě. Verze za míň bodů, protože pohyb je o dost víc než klepání nohou.",
    celebrates: true,
  },
  {
    id: "brazilie",
    czTime: "03:00",
    label: "Brazílie (Rio)",
    utcOffset: "-2",
    merge: null,
    intensity: "H",
    tradition: "V Riu se slaví na pláži Copacabana, všichni v bílém pro štěstí a mír. O půlnoci se jde k vodě a přeskakuje se sedm vln, u každé si něco přeješ. Házejí se bílé květiny do moře jako dar bohyni moře Iemanjá.",
    perlicka: "Těch bílých oblečení nejsou náhodou tisíce, je to skoro pravidlo. Bílá v Brazílii na Silvestra znamená mír a čistý start, takže Copacabana vypadá jako jedno obří bílé moře lidí. A pokud chceš extra štěstí, barva spodního prádla rozhoduje o tom, co tě čeká: červená pro lásku, žlutá pro peníze, bílá pro klid. Takže zatímco ty řešíš, jestli máš čisté triko, Brazilci strategicky plánují barvu trenek. Ty vole, dres code až do spodků.",
    challenge: "Přeskoč sedm vln. Nemáš moře? V klidu. Sedmkrát vyskoč na místě a u každého skoku si něco přej. Sedm skoků, sedm přání, jedno video. To je tvůj check-in.",
    symbolicPenaltyNote: "Když fakt nemůžeš skákat, udělej aspoň sedm dřepů nebo sedm hlubokých nádechů s přáním. Verze za míň bodů, protože skok přes vlnu má říz, co dřep nedožene.",
    celebrates: true,
  },
  {
    id: "argentina",
    czTime: "04:00",
    label: "Argentina",
    utcOffset: "-3",
    merge: null,
    intensity: "M",
    tradition: "V Argentině se o půlnoci sní dvanáct hroznů, jeden za každý úder a každý měsíc, a u každého se něco přeje. Kdo stihne všech dvanáct, má mít šťastný rok.",
    perlicka: "Perlička se chystá. Zatím ti musí stačit, že TADY zrovna bouchají šampus.",
    challenge: "Sněz dvanáct kousků čehokoliv rychle po sobě (hrozny ideálně, ale klidně dvanáct lupínků) a u každého si něco přej. Video toho zběsilého cpaní je check-in. Ano, díváme se na tebe, co to budeš zakuckávat ve čtyři ráno.",
    symbolicPenaltyNote: "Když nemáš dvanáct kousků jídla, polkni aspoň dvanáct loků vody za sebou. Verze za míň bodů, protože voda nepočítá tak jako jídlo.",
    celebrates: true,
  },
  {
    id: "newfoundland",
    czTime: "04:30",
    label: "Newfoundland, Kanada",
    utcOffset: "-3:30",
    merge: null,
    intensity: "M",
    tradition: "Newfoundland je rybářský kraj s vlastním podivným časem a drsným humorem. Je tu žertovný zvyk kissing the cod: na oslavách se líbá treska pro štěstí.",
    perlicka: "Perlička se chystá. Zatím ti musí stačit, že TADY zrovna bouchají šampus.",
    challenge: "Dej pusu rybě. Máš doma rybí konzervu, mraženou rybu nebo aspoň obrázek ryby v telefonu? Pusa na displej platí. Fotka toho polibku je check-in.",
    symbolicPenaltyNote: "Když fakt nemáš žádnou rybu ani fotku, dej pusu čemukoliv studenému z lednice. Verze za míň bodů, protože pravá (nebo aspoň vyfocená) ryba je celý vtip.",
    celebrates: true,
  },
  {
    id: "venezuela",
    czTime: "05:00",
    label: "Venezuela",
    utcOffset: "-4",
    merge: null,
    intensity: "L",
    tradition: "Ve Venezuele je zvyk, že kdo chce v novém roce cestovat, projde se o půlnoci s kufrem kolem domu nebo bloku. Čím dál dojdeš, tím dál se prý podíváš.",
    perlicka: "Perlička se chystá. Zatím ti musí stačit, že TADY zrovna bouchají šampus.",
    challenge: "Popadni kufr nebo batoh a projdi se s ním. Klidně jen po bytě, kolem stolu, na balkon a zpět. Video nebo fotka s kufrem v ruce je check-in.",
    symbolicPenaltyNote: "Když nemáš kufr, vem aspoň tašku a projdi se s ní. Verze za míň bodů, protože s taškou se moc daleko necestuje.",
    celebrates: true,
  },
  {
    id: "usa-newyork",
    czTime: "06:00",
    label: "USA, New York",
    utcOffset: "-5",
    merge: null,
    intensity: "M",
    tradition: "New York je ten slavný ball drop na Times Square: obří svítící koule sjede dolů v posledních deseti vteřinách roku a milion lidí v zimě odpočítává.",
    perlicka: "Perlička se chystá. Zatím ti musí stačit, že TADY zrovna bouchají šampus.",
    challenge: "Udělej vlastní mini ball drop. Vezmi ponožku (ideálně čistou, ale nebudeme kontrolovat) a nech ji pomalu padat při odpočtu od deseti. Video padající ponožky je tvůj check-in.",
    symbolicPenaltyNote: "Když se ti nechce hledat ponožku, nech spadnout cokoliv měkkého po ruce. Verze za míň bodů, protože ponožkový ball drop je prostě ikonický.",
    celebrates: true,
  },
  {
    id: "mexiko",
    czTime: "07:00",
    label: "Mexiko",
    utcOffset: "-6",
    merge: null,
    intensity: "L",
    tradition: "Mexiko v tuhle ranní hodinu jede klid a jídlo. Rodina, tamales, teplo. Pro tebe je to zastávka na nadechnutí před posledním blokem noci.",
    perlicka: "Perlička se chystá. Zatím ti musí stačit, že TADY zrovna bouchají šampus.",
    challenge: "Dej si něco k jídlu, cokoliv teplého nebo pořádného. Jsi vzhůru skoro celou noc, zasloužíš si to. Fotka jídla je check-in.",
    symbolicPenaltyNote: "Když fakt nemáš nic k jídlu, dej si aspoň teplý čaj nebo kafe. Verze za míň bodů, protože pořádné sousto tě na nohou udrží líp.",
    celebrates: true,
  },
  {
    id: "usa-colorado",
    czTime: "08:00",
    label: "USA, Colorado",
    utcOffset: "-7",
    merge: null,
    intensity: "M",
    tradition: "Colorado je hory, zima a sníh. Je to poslední navádějící zastávka před velkou kotvou na Pacifiku v 09:00, kde se bude skákat do ledové vody.",
    perlicka: "Perlička se chystá. Zatím ti musí stačit, že TADY zrovna bouchají šampus.",
    challenge: "Nalaď se na ledovou vodu, co přijde za hodinu. Opláchni si obličej studenou vodou a nahlas řekni 'jsem připravený'. Fotka mokrého ksichtu je check-in.",
    symbolicPenaltyNote: "Když se ti nechce k umyvadlu, přejeď si obličej aspoň studenou flaškou. Verze za míň bodů, protože pořádný šok vodou tě probere líp.",
    celebrates: true,
  },
  {
    id: "usa-pacifik",
    czTime: "09:00",
    label: "USA, Pacifik (LA)",
    utcOffset: "-8",
    merge: null,
    intensity: "MEGA",
    tradition: "Tohle je třetí MEGA kotva noci. Na západním pobřeží je populární Polar Bear Plunge: lidi na Nový rok skáčou do ledového oceánu nebo jezera, prý pro zdraví a čistou hlavu. Navedlo tě sem Chatham, Darwin, Brazílie a Colorado.",
    perlicka: "Perlička se chystá. Zatím ti musí stačit, že TADY zrovna bouchají šampus.",
    challenge: "Tvůj vlastní Polar Bear Plunge. Dej si na dvacet vteřin studenou sprchu, nebo si cákni ledovou vodu na krk a ruce. Video nebo fotka hned po tom je check-in téhle MEGA zóny.",
    symbolicPenaltyNote: "Když fakt nemáš koule na studenou sprchu, hoď si aspoň led do kalhot na pár vteřin. Verze za míň bodů, a hlavně, zasloužíš si ten mráz na blbším místě než na krku.",
    celebrates: true,
  },
  {
    id: "aljaska-marquesas",
    czTime: "10:00",
    label: "Aljaška + Marquesas Islands",
    utcOffset: "-9 / -9:30",
    merge: "Merge skupina: Aljaška + Marquesas Islands. Jeden check-in pro obě, jedna fotka stačí.",
    intensity: "L",
    tradition: "Aljaška je led a tma, oslava je spíš u krbu než venku. Marquesas jsou naopak tropické ostrovy v Pacifiku s vlastním zvláštním časem -9:30. Dohromady je to tvoje zóna na zotavení po ledové kotvě.",
    perlicka: "Perlička se chystá. Zatím ti musí stačit, že TADY zrovna bouchají šampus.",
    challenge: "Zotavovací zóna. Zabal se do deky, dej si něco teplého k pití a prostě pět minut nic nedělej. Fotka tebe v režimu lenochod je check-in za obě zóny.",
    symbolicPenaltyNote: "Když se ti nechce ani balit do deky, aspoň si na minutu zavři oči vsedě. Verze za míň bodů, protože pořádný oddech je víc než mrknutí.",
    celebrates: true,
  },
  {
    id: "havaj",
    czTime: "11:00",
    label: "Havaj",
    utcOffset: "-10",
    merge: null,
    intensity: "M",
    tradition: "Havaj je skoro poslední zastávka. Palmy, oceán, pohodová oslava s ohňostroji. Pro tebe je to předposlední nakopnutí před finále v Americké Samoe.",
    perlicka: "Perlička se chystá. Zatím ti musí stačit, že TADY zrovna bouchají šampus.",
    challenge: "Poslední pořádný nakop. Pusť nějaký letní banger a tancuj šedesát vteřin naplno, jako bys byl na pláži. Video tance je check-in.",
    symbolicPenaltyNote: "Když už fakt nemáš sílu na minutu, dej aspoň třicet vteřin. Verze za míň bodů, protože zkrácený tanec je zkrácený flex.",
    celebrates: true,
  },
  {
    id: "americka-samoa",
    czTime: "12:00",
    label: "Americká Samoa",
    utcOffset: "-11",
    merge: null,
    intensity: "MEGA",
    tradition: "Finále. Americká Samoa je poslední obydlené místo na planetě, co vstupuje do nového roku. Když slaví ona, celý svět už je uvnitř. Tohle je tvoje poslední MEGA zastávka a konec cesty.",
    perlicka: "Tady si uvědom tu šílenost: Americká Samoa a sousední stát Samoa jsou od sebe pár set kilometrů, ale dělí je skoro celý den. Jeden žije na začátku dne, druhý na konci. Dřív byla i Samoa na stejné straně jako Amerika, ale v roce 2011 kvůli obchodu s Austrálií a Novým Zélandem přeskočila přes datovou hranici a jeden celý den jim z kalendáře prostě vypadl. Lidi šli spát ve čtvrtek a vzbudili se v sobotu, pátek 30. prosince 2011 tam nikdy neexistoval. Ty vole, celý jeden den smazaný dekretem. A ty jsi teď dojel až na úplný konec téhle časové šílenosti.",
    challenge: "Finální přípitek celé noci. Zvedni skleničku a řekni nahlas jedno jediné slovo, co vystihuje celou tuhle noc. Jen jedno. Video nebo fotka toho posledního přípitku se slovem je tvůj závěrečný check-in.",
    symbolicPenaltyNote: "Když ti už došlo pití i hlas, napiš to jedno slovo aspoň do zprávy. Verze za míň bodů, protože finále si zaslouží, abys to řekl nahlas.",
    celebrates: true,
  },
];

export default ZONES;
